### ISSUE TITLE
Does not find Key Slot 1 password in xts-plain64 sha512

### ISSUE THREAD

**Issue by wesinator** [cryptcoffee/skul#5]
skul did not find the known password when checked using dict.
```
Magic: LUKS 0xba 0xbe
Version: 1
Disk UUID: 
Cipher name: aes
Cipher mode: xts-plain64
Hash Function: sha512
Master key len: 64 byte (512 bit)
Iterations: 35375
```

cryptsetup luksDump:
```
LUKS header information for /dev/sdX

Version:        1
Cipher name:    aes
Cipher mode:    xts-plain64
Hash spec:      sha512
Payload offset: 4096
MK bits:        512
MK digest:      
MK salt:        
MK iterations:  35375
UUID:           

Key Slot 0: DISABLED
Key Slot 1: ENABLED
        Iterations:             130611
        Salt:                   
        Key material offset:    512
        AF stripes:             4000
Key Slot 2: DISABLED
Key Slot 3: DISABLED
Key Slot 4: DISABLED
Key Slot 5: DISABLED
Key Slot 6: DISABLED
Key Slot 7: DISABLED
```

**Comment by wesinator** [comment]
Seems it isn't checking nonzero active key slots.

**Comment by pyno** [comment]
Hi @wesinator,

Sorry for the long delay, and thank you very much for reporting the issue.
I've dived into the problem and found that, despite we where correctly running the attack against all active keyslots, the key matherial we were checking against for correctness was wrong (for nonzero key slots). 

I'm working on a fix that will be soon available. I will also modify the interface so that it will be more clear which key slot skul is attacking.

Thank you very much again,
pyno
